### ISSUE TITLE
I am puzzled by the function of this code. 

### ISSUE THREAD

**Issue by wsysx123** [meagmohit/BLINK#2]
First of all, thank you for your rich paper! It is mentioned in this paper that this algorithm realizes an efficient eye movement detection algorithm, and can be reproduced by the code. But I found that the code must rely on the labels file to run, how does this reflect the original data judgment function? Thank you!

**Comment by meagmohit** [comment]
Hi,

The code relies on the labels part only to compute the accuracy of the algorithm (by comparing with the ground truth labels). Feel free to remove the lines after 362/363, and just print those variables.
